### ISSUE TITLE
A website for this?

### ISSUE THREAD

**Issue by olawalejuwonm** [BankkRoll/repo2pdf#11]
Can we have a website for this? Only take the repo url and process it on the cloud and respond with the pdf

**Comment by BankkRoll** [comment]
Hey @olawalejuwonm from me, no. This is a small project i made for myself and blew up a bit. You are free to contribute and make one! Would love to see it happen!

**Comment by olawalejuwonm** [comment]
It didn't work for me on local actually

**Comment by olawalejuwonm** [comment]
It didn't work for me on local, actually

**Comment by BankkRoll** [comment]
Could you explain your issue or error? Maybe can help.

**Comment by olawalejuwonm** [comment]
There was no error message.

It just hang up

**Comment by BankkRoll** [comment]
Please provide more info. have you installed it via npx or cloned it? Theres some type of logs when it starts, where is it hanging up? Are you trying with or without line numbers, highlighting ect?

**Comment by olawalejuwonm** [comment]
Via next and trying it with highlighting and page numbers

**Comment by BankkRoll** [comment]
you need to provider more info or i cannot help... Made a website, very limited ATM but basic. https://repo2pdf.vercel.app/
