### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by joserribeiro26** [BankkRoll/repo2pdf#16]
Estou recebendo esse erro na hora de dar o fetch nos arquivos do repositório. 

<img width="1504" alt="image" src="https://github.com/user-attachments/assets/9a54b63a-3566-4ea2-a598-083b926fc745">

**Comment by BankkRoll** [comment]
@joserribeiro26 can you please share the repo link you used? is it a super large repo?

**Comment by BankkRoll** [comment]
@joserribeiro26 Hey can you tell me the repo you used i tried a few large ones even react from meta. All seem to work fine?

**Comment by SonixSquad** [comment]
I have the same issue and I setup a public test repo (with just a readme file) to confirm if it was related to a private repo or not and although it worked, it also got the same error later when I tried again. It will intermittently work and then stop working again.

``Application error: a client-side exception has occurred (see the browser console for more information).``

https://github.com/[SonixSquad/Testrepo](https://github.com/SonixSquad/Testrepo)

**Comment by SonixSquad** [comment]
Heres the dev console details provided on the error specifics

Failed to load resource: the server responded with a status of 500 ()
create-420d82159595630e.js:1  Error fetching repository files: TypeError: Cannot read properties of undefined (reading 'map')
    at v (create-420d82159595630e.js:1:15857)
v @ create-420d82159595630e.js:1
framework-1751fec5da7e0462.js:25  TypeError: Cannot read properties of undefined (reading 'length')
    at S (create-420d82159595630e.js:1:9004)
    at ld (framework-1751fec5da7e0462.js:25:58401)
    at od (framework-1751fec5da7e0462.js:25:72731)
    at i (framework-1751fec5da7e0462.js:25:120263)
    at uI (framework-1751fec5da7e0462.js:25:99019)
    at framework-1751fec5da7e0462.js:25:98886
    at uM (framework-1751fec5da7e0462.js:25:98893)
    at ux (framework-1751fec5da7e0462.js:25:95645)
    at uS (framework-1751fec5da7e0462.js:25:94200)
    at x (framework-1751fec5da7e0462.js:49:1364)
l5 @ framework-1751fec5da7e0462.js:25
main-48a2be0192cdda09.js:1  TypeError: Cannot read properties of undefined (reading 'length')
    at S (create-420d82159595630e.js:1:9004)
    at ld (framework-1751fec5da7e0462.js:25:58401)
    at od (framework-1751fec5da7e0462.js:25:72731)
    at i (framework-1751fec5da7e0462.js:25:120263)
    at uI (framework-1751fec5da7e0462.js:25:99019)
    at framework-1751fec5da7e0462.js:25:98886
    at uM (framework-1751fec5da7e0462.js:25:98893)
    at ux (framework-1751fec5da7e0462.js:25:95645)
    at uS (framework-1751fec5da7e0462.js:25:94200)
    at x (framework-1751fec5da7e0462.js:49:1364)
Z @ main-48a2be0192cdda09.js:1
main-48a2be0192cdda09.js:1  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

**Comment by BankkRoll** [comment]
> I have the same issue and I setup a public test repo (with just a readme file) to confirm if it was related to a private repo or not and although it worked, it also got the same error later when I tried again. It will intermittently work and then stop working again.
> 
> `Application error: a client-side exception has occurred (see the browser console for more information).`
> 
> [https://github.com/[SonixSquad/Testrepo](https://github.com/SonixSquad/Testrepo)](https://github.com/%5BSonixSquad/Testrepo%5D(https://github.com/SonixSquad/Testrepo))

Hey thanks for this, going to try a bunch tomorrow and check why, assume its function timing out or GitHub api throwing error since github auth for cloning repos was removed when actual auth was added, Fixes coming tomorrow thanks

**Comment by BankkRoll** [comment]
Thank you all for your support! The issue has been resolved—it was related to the GitHub API key, but everything is working now, some repos may be super large and vercel function will timeout eventually but most should work just tried with mutliple different repos back to back to back on deployed version... 

 I'll be rolling out more updates soon, including improvements to image rendering and better code rendering features, especially now that we have paying customers. Stay tuned for more updates, and thanks again for your purchases!
