### ISSUE TITLE
Feature request - Deselect All folders / files

### ISSUE THREAD

**Issue by epenabella** [BankkRoll/repo2pdf#18]
Feature request - Deselect All folders / files

That way if the repo is big we can choose which files we want to add

**Comment by BankkRoll** [comment]
Hey thanks for this feedback will do! Think when i added the modal the select all doesn't deselect all anymore so will refix that and push changed!

**Comment by BankkRoll** [comment]
Changes are being pushed as I close this, and the requested feature has been added + little more! 

Thank you for your support and for suggesting this improvement—it helps enhance the experience for everyone, including yourself. I truly appreciate it! Feel free to open more issues, whether for new features or bug reports. Your feedback is always welcome. Thanks again!

https://github.com/user-attachments/assets/98cf3605-2ce4-4b13-95d6-92f4bc57438c
