### ISSUE TITLE
TypeError: Cannot read property 'width' of null

### ISSUE THREAD

**Issue by cowsaysfoo** [BankkRoll/repo2pdf#6]
Getting following error (whether using local or remote repo):

✔ Repository cloned successfully
✖ An error occurred
TypeError: Cannot read property 'width' of null
    at PDFDocument._initOptions (/root/.npm/_npx/11907/lib/node_modules/repo2pdf/node_modules/pdfkit/js/pdfkit.js:4078:34)
    at PDFDocument._text (/root/.npm/_npx/11907/lib/node_modules/repo2pdf/node_modules/pdfkit/js/pdfkit.js:3859:20)
    at PDFDocument.text (/root/.npm/_npx/11907/lib/node_modules/repo2pdf/node_modules/pdfkit/js/pdfkit.js:3897:17)
    at /root/.npm/_npx/11907/lib/node_modules/repo2pdf/dist/clone.js:147:38
    at Generator.next (<anonymous>)
    at fulfilled (/root/.npm/_npx/11907/lib/node_modules/repo2pdf/dist/clone.js:6:58)

**Comment by BankkRoll** [comment]
Hey @cowsaysfoo I apologize for the inconvenience you're experiencing I'll be happy to investigate the issue. Please help me answer a few questions to help the process.

1. Could you please provide the URL of the repository you're trying to clone? If it's a public repository, If not that's completely fine.
2. Could you specify whether you're using `npx repo2pdf` or `git clone https://github.com/BankkRoll/repo2pdf` & cloning the repository on your local machine?

Thank you for providing these details, as they will help me better understand the issue at hand.

**Comment by cowsaysfoo** [comment]
@BankkRoll Much appreciated! 
Sure--
1. Repo is [https://github.com/carlospolop/hacktricks](https://github.com/carlospolop/hacktricks ) (it's the source repo in markdown for a public gitbook..it's...massive, but pretty standard, formatting-wise)
2. using `npx repo2pdf`

**Comment by BankkRoll** [comment]
Hey @cowsaysfoo, I went ahead and fixed the issue.

I have tested it by [cloning-the-repository](https://github.com/BankkRoll/repo2pdf#installing-and-using-repo2pdf-by-cloning-the-repository) and got a success. (Note: It may work using `npx`, but I tested using the local version of `repo2pdf`, so it's not guaranteed.)

The one issue I'm still encountering is memory errors when applying some highlighting. (Please select 'NO' for the highlighting question.) I plan to revisit this later and refactor it to use streamable methods for better memory management.

Thanks for using repo2pdf! I'm going to close this issue as it's resolved. If I can further assist you, please don't hesitate to let me know or open a new issue. Your help keeps my products up-to-date for all use cases!
