### ISSUE TITLE
Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by Andro-Meta** [BankkRoll/repo2pdf#7]
✖ An error occurred
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:695:37)
    at Buffer.toString (node:buffer:865:14)
    at C:\Users\Owner\AppData\Local\npm-cache\_npx\0b76f6d2ca81e1a2\node_modules\repo2pdf\dist\clone.js:145:82
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Owner\AppData\Local\npm-cache\_npx\0b76f6d2ca81e1a2\node_modules\repo2pdf\dist\clone.js:6:58) {
  code: 'ERR_STRING_TOO_LONG'
  
  What can I do to fix this error?

**Comment by Andro-Meta** [comment]
I attempted to do this with a local install of ComfyUI. I then tried to do this with a the github repo and this was the error:

? Do you want to use a local repository? No
? Please provide a GitHub repository URL: https://github.com/comfyanonymous/ComfyUI
? Do you want to add line numbers to the PDF? Yes
? Do you want to add highlighting to the PDF? Yes
? Do you want to remove comments from the PDF? (Does not remove comments behind code on the same line) No
? Do you want to remove empty lines from the PDF? No
? Do you want to make one PDF per file? No
? Do you want to add page numbers to the PDF? Yes
? Please provide an output file name: comfyui
? Do you want to keep the cloned repository? No

Processing your request...

✔ Repository cloned successfully
⠦ Processing files... (219 processed)
<--- Last few GCs --->

[22776:00000143C2F7F4C0]    92543 ms: Mark-sweep 4066.6 (4139.1) -> 4054.6 (4142.8) MB, 1667.5 / 0.0 ms  (average mu = 0.094, current mu = 0.005) allocation failure; scavenge might not succeed
[22776:00000143C2F7F4C0]    95104 ms: Mark-sweep 4070.3 (4142.8) -> 4058.3 (4146.8) MB, 2553.0 / 0.0 ms  (average mu = 0.041, current mu = 0.003) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF77C6C194F node_api_throw_syntax_error+175855
 2: 00007FF77C646026 SSL_get_quiet_shutdown+59654
 3: 00007FF77C647D10 SSL_get_quiet_shutdown+67056
 4: 00007FF77D0F21F4 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF77D0DD582 v8::Isolate::Exit+674
 6: 00007FF77CF5F41C v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF77CF5C63B v8::internal::Heap::CollectGarbage+3963
 8: 00007FF77CF72873 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF77CF7311D v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF77CF828E0 v8::internal::Factory::NewFillerObject+816
11: 00007FF77CC73325 v8::internal::DateCache::Weekday+1349
12: 00007FF77D18F751 v8::internal::SetupIsolateDelegate::SetupHeap+558193
13: 00007FF6FD71ED48

**Comment by BankkRoll** [comment]
@Andro-Meta. I appreciate the detailed error log, the recent changes have increased the data processing load, and it needs to transitioned to a more memory-efficient approach, such as streaming or chunking, to handle large repositories effectively.

As a workaround,  try disabling some options like syntax highlighting and line numbers to reduce the processing load. I'll work on optimizing the code to handle larger data sets more efficiently soon just busy with some other things recently. Thanks

**Comment by Northloop** [comment]
Perfect. I'll give that a try shortly :)

**Comment by BankkRoll** [comment]
Thanks for using repo2pdf, let me know your results here so we can take care of this issue!

**Comment by Northloop** [comment]
It looks like the highlighting was the main problem. Everything worked with that one specifically not in use. Thank you!
