### ISSUE TITLE
Files added to `.gitignore` should not be appended to the PDF file

### ISSUE THREAD

**Issue by aniruddha-adhikary** [BankkRoll/repo2pdf#8]
## Action

I use repo2pdf on a `local` repository. It had a .gitignore excluding certain files.

## Expected behavior
I expected repo2pdf to ignore those files and patterns mentioned in gitignore.

## Actual behavior
Instead, repo2pdf included those files in gitignore.

**Comment by BankkRoll** [comment]
Hey, @aniruddha-adhikary I appreciate your feedback and sorry for the issues. I will take a look into this. Please check it was a `repo2pdf.ignore` you meant not a `.gitignore` to ignore certain file types. Ref- https://github.com/BankkRoll/repo2pdf?tab=readme-ov-file#configuration
